language: bash
services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - sed -ri 's/example.com/localhost/' blog.conf
  - cat blog.conf
  - docker-compose up -d
  - sleep 10
  - docker-compose restart blog
  - sleep 5
  - docker-compose ps
  - docker-compose exec blog ping -c 5 data
  - docker-compose exec blog ping -c 5 nginx
  - docker-compose exec blog python manage.py createsuperuser --user=test123 --email=test123@example.com --noinput
  - timeout 60 bash -c 'until $(curl -Isf -o /dev/null http://localhost:5967); do printf '.'; sleep 1; done'
  - timeout 60 bash -c 'until $(curl -Isf -o /dev/null http://localhost); do printf '.'; sleep 1; done'
